name: Continuous Deployment (Docker)

on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: ["CI Pipeline - Toolbox V2"]
    types: [completed]
    branches: [main]

jobs:
  build-and-push:
    if: >
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'push' && contains(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- L'ÉTAPE MAGIQUE POUR LES MINUSCULES ---
      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app_api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/toolbox-api:latest
            ghcr.io/${{ env.OWNER_LC }}/toolbox-api:${{ github.sha }}
            ghcr.io/${{ env.OWNER_LC }}/toolbox-api:${{ github.ref_name }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app_front/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/toolbox-front:latest
            ghcr.io/${{ env.OWNER_LC }}/toolbox-front:${{ github.sha }}
            ghcr.io/${{ env.OWNER_LC }}/toolbox-front:${{ github.ref_name }}